# Requests modülü 15.6

In [3]:
import requests

In [2]:
!pip install requests

Defaulting to user installation because normal site-packages is not writeable


In [1]:
# bir html herhangi bir web sitesi üzerinde kaynak kodlarını açıp üzerinde işlem yapabiliyorum
# json string bilgi olarak verir
# 19a kadar olanalrı geçtim çünkü işime pek yaramadı ihtiyacım olursa buradan dönüp
# bakacağım. webscrapinge örn

# 19.1 numpy nedir?

In [4]:
import numpy as np

In [3]:
py_list = [1,2,3,4,5,6,7,8,9] #listelerin yapamadığı birçok işi numpy ile yapabilirim

In [7]:
# numpy array oluşturuyorum yani dizi

nparray = np.array([1,2,3,4,5,6,7,8,9]) #array içine köşeli parantezlerle yazıyorum, bir liste göndeeriyorum bunu bir numpy dizisine çevirecek
print(type(nparray))
print(type(py_list))

<class 'numpy.ndarray'>
<class 'list'>


In [8]:
# çok boyutlu liste oluşturmak istersem
py_multi = [[1,2,3], [4,5,6], [7,8,9]]
npmulti = nparray.reshape(3,3) #reshape ile yeniden şekillendirebiliyorum bunun için 3e 3lük bir matris oluştur diyorum

print(py_multi)
print(npmulti)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(nparray.ndim) #ndim ile boyutuna bakıyorum bu bir boyutludur
print(npmulti.ndim) #bu iki boyutlu bir dizidir

1
2


In [10]:
print(nparray.shape) #tek boyutlu olduğu için dokuz diyor diğeri 3e 3
print(npmulti.shape)

(9,)
(3, 3)


# 19.2 numpy dizileri ile çalışma

In [11]:
import numpy as np

In [12]:
result = np.array([1,2,3,7,9]) #elemanlarını kendim elirttiğim bir dizi

print(result)

[1 2 3 7 9]


In [13]:
np.arange(1,10) #kendim belirmek itemediğim bir eleman oluşturdum np arrayi

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
result = np.arange(1,100,3) # 10 ile 100 arasında 3er rtan bir array
print(result)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]


In [16]:
result = np.zeros(10) #10 tane 0 olan bir array
result

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
result = np.ones(10) # oluşturulan sayılar floattır
result

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
result = np.linspace(0,100,5) #belirli bir sayı arasında 5 eş parçaay bölünen bir array oluşturmak istersem linspace metodunu kullanabilirim
print(result)

[  0.  25.  50.  75. 100.]


In [20]:
result = np.linspace(0,5,5)
print(result)

[0.   1.25 2.5  3.75 5.  ]


In [23]:
result = np.random.randint(0,10)
print(result) #her çalıştırdığımda 0 ile 10 arasında bir int sayı söyler en fazla 9 söyleyebilir

7


In [25]:
result = np.random.randint(20) # 0 ile 20 arasında üretir

result = np.random.randint(0,10,3)
print(result) #her seferinde 0 ile 10 arasında 3 tane farklı sayı gelir

[5 2 8]


In [28]:
resultt = np.random.rand(5) # 0 ile 1 arasında 5 sayı üretir
resultt

array([0.34001772, 0.69331822, 0.65051331, 0.05109022, 0.23508452])

In [31]:
resultt = np.random.randn(5) #randn dediğimde içine eksi değerler de girmiş olur
resultt

array([-1.49949647,  0.67969979, -0.97828522, -2.17925737,  0.88472459])

In [36]:
np_array = np.arange(50) # 0dan 50ye kadar bir dizi oluşturdum
np_multi=  np_array.reshape(5,10) # oluşturduğum diziyi 10arlık 5 parçaya böldüm

print(np_multi.sum(axis =1)) # satırların toplamını getirdi
print(np_multi.sum(axis =0)) #sütunların toplamı

[ 45 145 245 345 445]
[100 105 110 115 120 125 130 135 140 145]


In [53]:
rnd_numbers = np.random.randint(1,100,10) # 1 ile 100 arası 10 sayı
print(rnd_numbers)
result = rnd_numbers.max()
result = rnd_numbers.min()
result = rnd_numbers.mean() # sayıların ortalaması
result = rnd_numbers.argmax() #üretilen en büyük sayının index numarasını getirir
result = rnd_numbers.argmin() #üretilen en küçük sayının indexi
result

[66 60 45 15 10 97 63 71 78  6]


9

# 19.3 numpy dizilerinin indexlenmesi

In [54]:
import numpy as np

In [63]:
numbers = np.array([0,5,10,15,20,25,50,75])

result = numbers[5]
result = numbers[-1] #pythonda nasıl listeelemanlarını ulaşabiliyorsam aynı şekilde ulaşabilirm
result = numbers[0:3] #0 5 10 değerleri gelir
result = numbers[:3]
result = numbers[3:] # sona kadar gider
result = numbers[::] #tüm listeyi yazdırır
result = numbers[::-1] #terse çevirdim
result = numbers[::-2] #tersten 2şer



print(result)

[75 25 15  5]


In [74]:
numbers2 = np.array([[0,5,10],[15,20,25],[50,75,85]])
result = numbers2[0]
result = numbers2[0,2] #ekstradan kutucuk açmadan yine yazdırabilirim bu şekilde ilk 3lüden 2. index demek
result = numbers2[:,2] # tüm satırları seçiyorum : ile ve 2. indexlerini alıyorum birden fazla değer aldım bu şekilde yani 10 25 ve 85 değerleri gelecek
result = numbers2[:,0] #tüm satırlar ve 0. indexler
result = numbers2[:,0:2] #tüm satılar seçildi ve 0 ile 2. index aralığındaki elemanlar geldi yani hepsinden ilk iki eleman geldi
result = numbers2[-1,:] #son satır içindeki tüm sütunlar 1. kolon 2. kolon ve 3. kolon geldi son elemandaki
result = numbers2[:2,:2] # ilk iki satır ve ilk iki kolon




print(result)

[[ 0  5]
 [15 20]]


In [77]:
arr1 = np.arange(0,10)
arr2 = arr1 # referans kopyalaması yaptım

print(arr1)
print(arr2) #ikisi de aynı diziye karşılık geldi çünkü arr1 adresinin kopyasını arr2ye verdim

arr2[0] = 20

print(arr1)
print(arr2) #değişiklik ikisinde de oldu çünkü bellek üzerinde aynı adres üzerinde tutulan aynı verilere yeni tanımlama yaptım

#arr1 = arr1.copy() yaparsam arr1 kopyası olmuş olacak ve arr2ye copyi tanımlasam farklı alanlarda tutulan veriler olacağı için değişiklik sadece arr2de olacak

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[20  1  2  3  4  5  6  7  8  9]
[20  1  2  3  4  5  6  7  8  9]


# 19.4 numpy dizi operasyonları

In [78]:
import numpy as np

In [109]:
numbers1 = np.random.randint(10,100,6)
numbers2 = np.random.randint(10,100,6) #rastgele üretilen 2 tane dizi

print(numbers1, numbers2)

result = numbers1 + numbers2
result = numbers1 + 10 #unmber1 deki elemanlara 10 ekledim
result = numbers1 - numbers2 # çıkartrrım
result = numbers1 - 10
result = numbers1 * numbers2
result = numbers1 * 10
result = numbers1 / numbers2
result = numbers1 / 10

result = np.sin(numbers1) # numbers1 in sinüsünü aldım
result = np.cos(numbers2) #numbers2 nin cosünüsünü aldım
result = np.sqrt(numbers1) #her elemanın karekökünü alır
result = np.log(numbers1) #her değerim logaritmasını alır

multinumbers1 = numbers1.reshape(2,3)
multinumbers2 = numbers2.reshape(2,3)

print(multinumbers1) #2 satır 3 kolon
print(multinumbers2) # elemanları 10 ile 100 arasında olan iki farklı matris geldi

result = np.vstack((multinumbers1,multinumbers2)) #dikey olarak birleştirme işlemi yapıyor ve tek parametre şeklinde göndermem grektiği için bir parantez içine alıyorum
result = np.hstack((multinumbers1,multinumbers2)) #yatay olarak birleştirir

result = numbers1 >= 50 #elemanların hepsine bakar her elemanın 5ten büyük olup olmadığını kntrol eder ve bool değer gönderir

result = numbers1 %2 == 0 #sayılar çift mi diye kontrol ettirdim
print(numbers1[result]) #sorguladığım değerlerin True olanları bana liste iiçnde gelecek


print(result) #ikisini matemateiksel olarak aynı indexteki elemanları toplar yeni dizi yazdırır


[84 72 23 11 19 99] [28 96 41 62 21 43]
[[84 72 23]
 [11 19 99]]
[[28 96 41]
 [62 21 43]]
[84 72]
[ True  True False False False False]


# 19.5 python numpy demo

In [ ]:
#1- (10,15,30,45,60) değerlerine sahip umpy dizisini oluşturun
#2- (5-15) arasındaki sayılarla numpy dizisi oluşturun
#3-(50-100) arasında 5'er 5'er artarak numpy dizisi oluşturun
#4- 10 elemanlı 0lardan oluşan bir dizi oluşturun
#5- 10 elemanlı 1lerden oluşan bir dizi oluşturun
#6- (0-100) arasında eşit aralıklarla 5 sayı üretin
#7- (10-30) arasında rastgele 5 tane tamsayı üretin
#8- [-1 ile 1] arasında 10 adet sayı üretin
#9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturun
#10- üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız
#11- üretilen matrisin en büyük en küçük ve ortalamasını yazdırın
#12- üretilen matrisin en büyük değerinin indexi kaçtır
#13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçin
#14- üretilen dizinin elemanların ıtersten yazdırın
#15- üretilen matrisin ilk satırını yazdırın
#16- üretilen matrisin 2.satır ve 3.sütundaki eleamnı hangisidir
#17- üretilen matrisin tüm satırlardaki ilk elemanını seçiniz
#18- üretilen matrisin her bir elemanın karesini alınız
#19- üretilen matris elemanlarının hangisi pozitif çift sayıdır?
#(aralığı -50,+50 arasında yapınız)